### ISSUE TITLE
add to pypi

### ISSUE THREAD

**Issue by furlongm** [genotrance/fru-tool#11]
Could you add this tool to pypi? It would be easier to install, and also useful to people who have pypi mirrors but no external internet access.

**Comment by kurtmckee** [comment]
Marcus, I've published my current code to PyPI as an alpha release. Please note that there may be breaking changes, so it's released as 4.0.0a1. If you install it you'll have a "frutool" CLI that you can interact with.

Preliminary testing indicates that PyInstaller can package this as a standalone executable as well, so you can distribute this to end users (perhaps they're doing motherboard replacements, etc).

**Comment by genotrance** [comment]
Hello @kurtmckee - would you like access to maintain this repo going forward? I added @k5jj some time ago but considering all the work you have put in, will make sense for you to own this going forward.

**Comment by kurtmckee** [comment]
@genotrance, that works for me. I anticipate taking the tool in a direction that supports both a strong CLI and strong API. I'm using this in production at my company but also working to get this released as a full CLI tool for customer-facing support personnel who have to swap out motherboards.

I may also take this in a direction that adds support for a full GUI so that it's a little easier for end users. If those changes sound okay to you then I accept write access to your repo, and I'm grateful to be able to work with you on the project, instead of going it alone!

**Comment by genotrance** [comment]
Hello @kurtmckee - I've added you as a collaborator here. Feel free to drive the tool forward as you see fit.

**Comment by kurtmckee** [comment]
Thanks Ganesh! I should be able to pick up this work again soon, now that end-of-quarter is over. =)

**Comment by kurtmckee** [comment]
@furlongm Version 4 has been released and is available on PyPI.
