### ISSUE TITLE
add option to generate fru.ini from current fru data?

### ISSUE THREAD

**Issue by furlongm** [genotrance/fru-tool#12]
This is a wish list item, would be nice to generate an fru.ini to start with from the current fru data.

**Comment by kurtmckee** [comment]
Hey Marcus, I'm overhauling fru-tool so that it is easier for end-users to interact with. I have migrated from INI files to TOML files for increased capabilities in the file format. With that I have also added the ability to output an empty text file, or to dump a binary FRU file to TOML format.

Note that the TOML format looks similar to an INI file, but has far better definitions for what it actually is and how the data is represented. I think the TOML format won't cause a significant cognitive load on end users compared to INI.

**Comment by kurtmckee** [comment]
@furlongm The tool is now able to generate FRU files in TOML format. You can run this command to generate a blank TOML file with some instructions for editing at the top:

```
frutool sample edit_me.toml
```
